id = "zed-ream-language"
name = "Zed Ream Language"
version = "0.0.1"
schema_version = 1
authors = ["Khaumi <Khaumi@khaumi.com>"]
description = "Language support for Ream"
repository = "https://github.com/khaumi/zed-ream-language"

[grammars.ream]
repository = "https://github.com/IlluminateEC/tree-sitter-ream.git"
rev = "92569ebcffc1c2c308f4b6232327953aa4fc9666"
